# Generated by Django 2.0.2 on 2018-05-12 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycmprecord',
            name='company',
            field=models.ForeignKey(on_delete=True, to='market.Company'),
        ),
        migrations.AlterField(
            model_name='investmentrecord',
            name='company',
            field=models.ForeignKey(on_delete=True, to='market.Company'),
        ),
        migrations.AlterField(
            model_name='investmentrecord',
            name='user',
            field=models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(on_delete=True, to='market.Company'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
