# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-03 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20180430_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='company',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='company',
            name='temp_stocks_bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='temp_stocks_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='stocks_remaining',
            field=models.IntegerField(default=models.IntegerField(default=0)),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
