# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-25 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_net_worth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
