# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-29 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20180429_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCMPRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Company')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
