# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-29 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-cash', 'coeff_of_variation']},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='net_worth',
            new_name='cash',
        ),
    ]
