# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-29 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180429_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loan_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='loan_count_absolute',
            field=models.IntegerField(default=1),
        ),
    ]
