# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-25 02:28
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180424_0430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-net_worth', 'timestamp']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='loan',
        ),
        migrations.AlterField(
            model_name='user',
            name='net_worth',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000'), max_digits=20),
        ),
    ]
