# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-03 06:12
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='loan',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000'), max_digits=20),
        ),
    ]
