# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 05:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_transaction_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentrecord',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='market.Company'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='investmentrecord',
            unique_together=set([('user', 'company')]),
        ),
    ]
